# Site settings
title: Sean Clarke Designs
header-img: img/home-bg.png
email: xseanclarke@gmail.com
copyright_name: SCDesigns
description: > # this means to ignore newlines until "baseurl:"
  A picture is worth a thousand words. Or however many I manage to write
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  SCDesigns
learn_profile: SCDesigns
email_username: xseanclarke@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
